name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # once a day
  workflow_dispatch: # manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions: # 👈 required for pushing
      contents: write

    steps:
      - name: Generate Snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: imshravan26
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
