name: Test Meme Update

on:
  workflow_dispatch: # Manual trigger only
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/test-meme.yml"

permissions:
  contents: write
  actions: read

jobs:
  test-meme:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Debug environment
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "Scripts directory:"
          ls -la scripts/ || echo "Scripts directory not found"
          echo "Workflow directory:"
          ls -la .github/workflows/ || echo "Workflow directory not found"

      - name: Test meme generator
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: |
          echo "Testing meme generator..."
          node scripts/update_meme.js || echo "Meme generator failed"

      - name: Check git status
        run: |
          echo "Git status:"
          git status
          echo "Git log (last 3 commits):"
          git log --oneline -3

      - name: Check if files changed
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Files changed:"
            git status --porcelain
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No files changed"
          fi

      - name: Test commit (dry run)
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          echo "Would commit these changes:"
          git diff --name-only
          echo "Test successful - not actually committing"
